spring:
  profiles:
    active: production
---

spring:
  profiles: development
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_recipe
    username: recipe_user
    password: recipe
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    
---

spring:
  profiles: production