spring:
  profiles:
    active: production
---

spring:
  profiles: development
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

---

spring:
  profiles: production