spring:
  profiles:
    active: production
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/db_recipe
    username: recipe_user
    password: recipe
    
---

spring:
  profiles: production
  datasource:
      url: jdbc:mysql://localhost:3306/db_recipe
      username: recipe_user
      password: recipe